### ISSUE TITLE
Build Error - Can't find StaticMesh 'MiniSuperHealth'

### ISSUE THREAD

**Issue by ds8k** [Deaod/UTComp#6]
Getting an error when attempting to build:

```
Log: New File, Existing Package (Package UTCompv18c, Package MiniSuperHealth)
Warning: Failed to load 'minimegatex': Can't find file for package 'minimegatex'
Warning: Failed to load 'StaticMeshes/MiniSuperHealth.usx': Can't find file for package 'minimegatex'
Warning: Failed loading package: Can't find file for package 'minimegatex'
Log: Failed loading package: Can't find file for package 'minimegatex'

Error: F:\SteamLibrary\steamapps\common\Unreal Tournament 2004\UTCompv18c\Classes\Forward_MiniSuperHealthPack.uc(14) : Error, Can't find StaticMesh 'MiniSuperHealth'
```

**Comment by cclecle** [comment]
Same here, but I managed to fix it ! :)
I did not know if it was caused by my linux (wine) env or not, so now I guess not !

=> You must copy **both** textures and static mesh files in the main UT2k4 directory and then it work.
=> You may have miss minimegatex.utx from textures I guess

I also would have love textures spelled **T**extures  ..

Readme and/or build.bat updated needed ?
